version: '3'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
      - internal

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: r00t

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
      - internal

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: traefikdb
      MYSQL_USER: traefik
      MYSQL_PASSWORD: highway
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal
    labels:
      - "traefik.enable=false"

networks:
  web:
    external: true
  internal:
    external: false

volumes:
  db_data:
