---
# This playbook configures logging and auditing settings for Windows and Rocky Linux servers.

- name: Configure logging and auditing
  hosts: all
  gather_facts: yes

  tasks:
    # --- System Administration ---
    - name: Configure Windows Event Logging - Set Application Log Size
      win_eventlog:
        name: Application
        maximum_size: 64MB
        overflow_action: OverwriteAsNeeded
      when: ansible_os_family == "Windows"

    - name: Configure rsyslog (Rocky Linux)
      template:
        src: rsyslog.conf.j2
        dest: /etc/rsyslog.conf
      notify: Restart rsyslog
      when: ansible_os_family == "RedHat"

    # --- System Hardening ---
    - name: Enable PowerShell module logging
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\PowerShell\ModuleLogging
        name: EnableModuleLogging
        data: 1  # Enable module logging
        type: dword
      when: ansible_os_family == "Windows"

    - name: Configure auditd (Rocky Linux)
      template:
        src: audit.rules.j2
        dest: /etc/audit/rules.d/audit.rules
      notify: Restart auditd
      when: ansible_os_family == "RedHat"

    # --- AD GPO Hardening ---
    - name: Configure advanced audit policy - Enable Base Auditing - Using win_regedit
      win_regedit:
        path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Audit
        name: AuditBaseObjects
        data: 1  # Enable base auditing
        type: dword
      when: inventory_hostname in groups['windows']

    - name: Enable auditing for account logon events - Using win_regedit
      win_regedit:
        path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Audit
        name: AuditAccountLogon
        data: 3  # Audit Success and Failure
        type: dword
      when: inventory_hostname in groups['windows']

    - name: Enable auditing for object access - Using win_regedit
      win_regedit:
        path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Audit
        name: AuditObjectAccess
        data: 3  # Audit Success and Failure
        type: dword
      when: inventory_hostname in groups['windows']

  handlers:
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted
      when: ansible_os_family == "RedHat"

    - name: Restart auditd
      service:
        name: auditd
        state: restarted
      when: ansible_os_family == "RedHat"
