---
- name: Configure logging and auditing
  hosts: all
  gather_facts: yes

  tasks:
    # System Administration
    - name: Configure Windows Event Logging
      win_eventlog:
        name: Application
        maximum_size: 64MB
        overflow_action: OverwriteAsNeeded
      when: ansible_os_family == "Windows"

    - name: Configure rsyslog (Rocky Linux)
      template:
        src: rsyslog.conf.j2
        dest: /etc/rsyslog.conf
      notify: Restart rsyslog
      when: ansible_os_family == "RedHat"

    # System Hardening
    - name: Enable PowerShell module logging
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\PowerShell\ModuleLogging
        name: EnableModuleLogging
        data: 1
        type: dword
      when: ansible_os_family == "Windows"

    - name: Configure auditd (Rocky Linux)
      template:
        src: audit.rules.j2
        dest: /etc/audit/rules.d/audit.rules
      notify: Restart auditd
      when: ansible_os_family == "RedHat"

    # AD DS GPO Hardening (for Windows hosts)
    - name: Configure advanced audit policy
      win_gpo_reg:
        name: Advanced Audit Policy Configuration
        state: present
        key: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Audit
        value: AuditBaseObjects
        data: 1
        type: dword
      when: inventory_hostname in groups['windows']

    - name: Enable auditing for account logon events
      win_gpo_reg:
        name: Audit Account Logon Events
        state: present
        key: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Audit
        value: AuditAccountLogon
        data: 3
        type: dword
      when: inventory_hostname in groups['windows']

    - name: Enable auditing for object access
      win_gpo_reg:
        name: Audit Object Access
        state: present
        key: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Audit
        value: AuditObjectAccess
        data: 3
        type: dword
      when: inventory_hostname in groups['windows']

  handlers:
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted
      when: ansible_os_family == "RedHat"

    - name: Restart auditd
      service:
        name: auditd
        state: restarted
      when: ansible_os_family == "RedHat"
