---
- name: Install Nginx and open port 80
  hosts: nginx
  become: yes

  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: Start and enable Nginx service
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Open port 80 in firewalld
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Reload firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
